#!/usr/bin/env python
"""todo

usage: todo [-v] add <item>
       todo [-v] remove (<item> | <number>)
       todo [-v] show [<number>]
       todo (-h --version)

Options:
    -v --verbose  Show debug and info messages.
    -h --help     Show this message.
    --version     Show version.
"""

from docopt import docopt
import os


args = docopt(__doc__, version = "0.1a")
def vprint(string):
    if args["--verbose"]:
        print(string)


filepath = "~/.local/share/todo/list"

if not os.path.exists(os.path.dirname(filepath)):
    vprint("{} not found, creating\
            directories.".format(os.path.dirname(filepath)))
    os.makedirs(os.path.dirname(filepath))

if not os.path.isfile(filepath):
    vprint("{} not found, creating file.".format(filepath))
    f = open(filepath, 'w')
    f.close()


if args["add"]:
    vprint("Appending '{}' to todo list.".format(args["<item>"]))

    f = open(filepath, 'a')
    f.write("{}\n".format(args["<item>"]))
    f.close()

elif args["remove"]:
    if args["<item>"]:
        vprint("Attempting to remove '{}' from todo list.".format(args["<item>"]))
    elif args["<number>"]:
        vprint("Attempting to remove item {} from todo list.".format(args["<number>"]))

elif args["show"]:
    if args["<number>"]:
        vprint("Showing todo list item number {}.".format(args["<number>"]))

        f = open(filepath, 'r')
        for i, line in enumerate(f, start=1):
            if i == int(args["<number>"]):
               print("{}: {}".format(i, line), end="")

        f.close()

    else:
        vprint("Showing todo list.")

        f = open(filepath, 'r')
        print("TODO:")
        for line in enumerate(f, start=1):
            print("{}: {}".format(*line), end="")

        f.close()
